name: shoe_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_animate: ^4.1.1+1
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: ^0.3.2
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/shoe/
    - assets/image/
    - assets/icon/
    - shorebird.yaml
